# Generated by Django 6.1.1 on 2026-09-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_costumer',
            new_name='is_customer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
